In [3]:
!aws s3 cp s3://amazon-ml-challenge-aayushi/6ab10eb3b23ba_student_resource/ ./6ab10eb3b23ba_student_resource/ --recursive

download: s3://amazon-ml-challenge-aayushi/6ab10eb3b23ba_student_resource/__MACOSX/._student_resource to 6ab10eb3b23ba_student_resource/__MACOSX/._student_resource
download: s3://amazon-ml-challenge-aayushi/6ab10eb3b23ba_student_resource/__MACOSX/student_resource/._.DS_Store to 6ab10eb3b23ba_student_resource/__MACOSX/student_resource/._.DS_Store
download: s3://amazon-ml-challenge-aayushi/6ab10eb3b23ba_student_resource/__MACOSX/student_resource/._Documentation_template.md to 6ab10eb3b23ba_student_resource/__MACOSX/student_resource/._Documentation_template.md
download: s3://amazon-ml-challenge-aayushi/6ab10eb3b23ba_student_resource/__MACOSX/student_resource/dataset/train/._train_source3.tsv to 6ab10eb3b23ba_student_resource/__MACOSX/student_resource/dataset/train/._train_source3.tsv
download: s3://amazon-ml-challenge-aayushi/6ab10eb3b23ba_student_resource/__MACOSX/student_resource/dataset/train/._train_source2.tsv to 6ab10eb3b23ba_student_resource/__MACOSX/student_resource/dataset/train/._train_source2.tsv
download: s3://amazon-ml-challenge-aayushi/6ab10eb3b23ba_student_resource/__MACOSX/student_resource/dataset/._.DS_Store to 6ab10eb3b23ba_student_resource/__MACOSX/student_resource/dataset/._.DS_Store
download: s3://amazon-ml-challenge-aayushi/6ab10eb3b23ba_student_resource/__MACOSX/student_resource/dataset/._test to 6ab10eb3b23ba_student_resource/__MACOSX/student_resource/dataset/._test
download: s3://amazon-ml-challenge-aayushi/6ab10eb3b23ba_student_resource/__MACOSX/student_resource/dataset/._train to 6ab10eb3b23ba_student_resource/__MACOSX/student_resource/dataset/._train
download: s3://amazon-ml-challenge-aayushi/6ab10eb3b23ba_student_resource/student_resource/Documentation_template.md to 6ab10eb3b23ba_student_resource/student_resource/Documentation_template.md
download: s3://amazon-ml-challenge-aayushi/6ab10eb3b23ba_student_resource/__MACOSX/student_resource/utils/._validate_submission.py to 6ab10eb3b23ba_student_resource/__MACOSX/student_resource/utils/._validate_submission.py
download: s3://amazon-ml-challenge-aayushi/6ab10eb3b23ba_student_resource/student_resource/.DS_Store to 6ab10eb3b23ba_student_resource/student_resource/.DS_Store
download: s3://amazon-ml-challenge-aayushi/6ab10eb3b23ba_student_resource/__MACOSX/student_resource/dataset/train/._train_ground_truth.tsv to 6ab10eb3b23ba_student_resource/__MACOSX/student_resource/dataset/train/._train_ground_truth.tsv
download: s3://amazon-ml-challenge-aayushi/6ab10eb3b23ba_student_resource/__MACOSX/student_resource/dataset/test/._test_source1.tsv to 6ab10eb3b23ba_student_resource/__MACOSX/student_resource/dataset/test/._test_source1.tsv
download: s3://amazon-ml-challenge-aayushi/6ab10eb3b23ba_student_resource/student_resource/README.md to 6ab10eb3b23ba_student_resource/student_resource/README.md
download: s3://amazon-ml-challenge-aayushi/6ab10eb3b23ba_student_resource/__MACOSX/student_resource/._dataset to 6ab10eb3b23ba_student_resource/__MACOSX/student_resource/._dataset
download: s3://amazon-ml-challenge-aayushi/6ab10eb3b23ba_student_resource/__MACOSX/student_resource/._utils to 6ab10eb3b23ba_student_resource/__MACOSX/student_resource/._utils
download: s3://amazon-ml-challenge-aayushi/6ab10eb3b23ba_student_resource/student_resource/dataset/.DS_Store to 6ab10eb3b23ba_student_resource/student_resource/dataset/.DS_Store
download: s3://amazon-ml-challenge-aayushi/6ab10eb3b23ba_student_resource/student_resource/dataset/test/test_source1.tsv to 6ab10eb3b23ba_student_resource/student_resource/dataset/test/test_source1.tsv
download: s3://amazon-ml-challenge-aayushi/6ab10eb3b23ba_student_resource/__MACOSX/student_resource/dataset/test/._test_source2.tsv to 6ab10eb3b23ba_student_resource/__MACOSX/student_resource/dataset/test/._test_source2.tsv
download: s3://amazon-ml-challenge-aayushi/6ab10eb3b23ba_student_resource/__MACOSX/student_resource/dataset/test/._test_source3.tsv to 6ab10eb3b23ba_student_resource/__MACOSX/student_resource/dataset/test/._test_source3.tsv
download: s3://amazon-ml-challenge-aayushi/6ab10eb3b23ba_student_resource/__MACOSX/student_resource/._README.md to 6ab10eb3b23ba_student_resource/__MACOSX/student_resource/._README.md
download: s3://amazon-ml-challenge-aayushi/6ab10eb3b23ba_student_resource/__MACOSX/student_resource/dataset/train/._train_source1.tsv to 6ab10eb3b23ba_student_resource/__MACOSX/student_resource/dataset/train/._train_source1.tsv
download: s3://amazon-ml-challenge-aayushi/6ab10eb3b23ba_student_resource/student_resource/dataset/train/train_source2.tsv to 6ab10eb3b23ba_student_resource/student_resource/dataset/train/train_source2.tsv
download: s3://amazon-ml-challenge-aayushi/6ab10eb3b23ba_student_resource/student_resource/dataset/test/test_source3.tsv to 6ab10eb3b23ba_student_resource/student_resource/dataset/test/test_source3.tsv
download: s3://amazon-ml-challenge-aayushi/6ab10eb3b23ba_student_resource/student_resource/utils/validate_submission.py to 6ab10eb3b23ba_student_resource/student_resource/utils/validate_submission.py
download: s3://amazon-ml-challenge-aayushi/6ab10eb3b23ba_student_resource/student_resource/dataset/train/train_ground_truth.tsv to 6ab10eb3b23ba_student_resource/student_resource/dataset/train/train_ground_truth.tsv
download: s3://amazon-ml-challenge-aayushi/6ab10eb3b23ba_student_resource/student_resource/dataset/train/train_source1.tsv to 6ab10eb3b23ba_student_resource/student_resource/dataset/train/train_source1.tsv
download: s3://amazon-ml-challenge-aayushi/6ab10eb3b23ba_student_resource/student_resource/dataset/test/test_source2.tsv to 6ab10eb3b23ba_student_resource/student_resource/dataset/test/test_source2.tsv
download: s3://amazon-ml-challenge-aayushi/6ab10eb3b23ba_student_resource/student_resource/dataset/train/train_source3.tsv to 6ab10eb3b23ba_student_resource/student_resource/dataset/train/train_source3.tsv

In [5]:
with open('README.md','r',encoding='utf-8') as f:
    print(f.read())

# Amazon-ml-challenge

In [6]:
!aws s3 cp s3://amazon-ml-challenge-aayushi/6ab10eb3b23ba_student_resource/student_resource/dataset/train/train_source1.tsv - | head -5

entity_id	business_name	business_address	country
S1-925783039	Orelee's Barbershop	1795 Westchester Drive, High Point, NC	US
S1-773889195	Prime Money	17560 Ellis Road, Tahlequah, OK	US
S1-377745466	B+ Retail Inc	1712 Montebello Avenue, Phoenix, AZ	US
S1-133037285	Christ Chapel	2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD	US
download failed: s3://amazon-ml-challenge-aayushi/6ab10eb3b23ba_student_resource/student_resource/dataset/train/train_source1.tsv to - [Errno 32] Broken pipe

In [7]:
!aws s3 cp s3://amazon-ml-challenge-aayushi/6ab10eb3b23ba_student_resource/student_resource/dataset/train/train_source2.tsv - | head -5

entity_id	business_name	business_address	country
S2-166376419	राम मार्केटिंग प्राइवेट लिमिटेड	KH NO. -570/13, NEW DELHI, WEST DELHI, Delhi	India
S2-764573417	-- Holloway Peak Inc Seafood	105 ELM ST, MORGANTON, NC	US
S2-639257739	आदित्य प्रॉपर्टीज एलएलपी	G-3/571, GULMOHAR COLONY, BHOPAL, Madhya Pradesh	India
S2-163963287	Summit Inc	GREENSBORO, NC, 19 1/2 STARDUST TRAIL	US
download failed: s3://amazon-ml-challenge-aayushi/6ab10eb3b23ba_student_resource/student_resource/dataset/train/train_source2.tsv to - [Errno 32] Broken pipe

In [8]:
!aws s3 cp s3://amazon-ml-challenge-aayushi/6ab10eb3b23ba_student_resource/student_resource/dataset/train/train_source3.tsv - | head -5

entity_id	business_name	business_address	country
S3-202863386	wilfordhancock.com	Mack Rd, Haltom City, Texas	US
S3-859268022	International South Consultants Private Ltd		India
S3-22467283	LLC Moncada Léarning Center	5780 Fawn Ct, Fort Worth, Texas	US
S3-671162755	Moyna's Coffee	1 Ivanhoe Ave, PO Box 6009, Cincinnati, Ohio	US
download failed: s3://amazon-ml-challenge-aayushi/6ab10eb3b23ba_student_resource/student_resource/dataset/train/train_source3.tsv to - [Errno 32] Broken pipe

In [9]:
!aws s3 cp s3://amazon-ml-challenge-aayushi/6ab10eb3b23ba_student_resource/student_resource/dataset/train/train_ground_truth.tsv - | head -10

source1_entity_id	matched_entity_ids
S1-965667	S2-681193310,S2-743505751,S3-775321672,S3-11291185,S3-860443364
S1-55344266	S2-249013014,S2-197070651,S3-478195123,S3-384364074
S1-343815751	S2-790675320,S2-479876582,S3-878454467
S1-656753428	S2-153058913,S2-24659151,S3-679606215
S1-102811957	S2-478959098,S2-553508714,S2-625774905,S3-728090388,S3-928796641,S3-449308785
S1-18727616	S2-755677256,S3-187831601,S3-641489370,S3-476250621
S1-318373630	S2-660036492,S3-804600254
S1-86989137	S3-274817120,S3-312496301
S1-29845983	S2-648035184,S3-588502663
download failed: s3://amazon-ml-challenge-aayushi/6ab10eb3b23ba_student_resource/student_resource/dataset/train/train_ground_truth.tsv to - [Errno 32] Broken pipe

In [11]:
with open("README.md","r",encoding="utf-8") as f:
    print(f.read())

# Amazon-ml-challenge

In [23]:
import pandas as pd

source1 = pd.read_csv("6ab10eb3b23ba_student_resource/student_resource/dataset/train/train_source1.tsv", sep="\t", nrows=5)
source2 = pd.read_csv("6ab10eb3b23ba_student_resource/student_resource/dataset/train/train_source2.tsv", sep="\t", nrows=5)
source3 = pd.read_csv("6ab10eb3b23ba_student_resource/student_resource/dataset/train/train_source3.tsv", sep="\t", nrows=5)
group = pd.read_csv("6ab10eb3b23ba_student_resource/student_resource/dataset/train/train_ground_truth.tsv", sep="\t", nrows=10)

print(source1.columns.tolist())
print(source2.columns.tolist())
print(source3.columns.tolist())
print(group.columns.tolist())

['entity_id', 'business_name', 'business_address', 'country']
['entity_id', 'business_name', 'business_address', 'country']
['entity_id', 'business_name', 'business_address', 'country']
['source1_entity_id', 'matched_entity_ids']

In [24]:
source1.head()

,entity_id,business_name,business_address,country
0,S1-925783039,Orelee's Barbershop,"1795 Westchester Drive, High Point, NC",US
1,S1-773889195,Prime Money,"17560 Ellis Road, Tahlequah, OK",US
2,S1-377745466,B+ Retail Inc,"1712 Montebello Avenue, Phoenix, AZ",US
3,S1-133037285,Christ Chapel,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",US
4,S1-755362802,Prabhav Business Center,"797, Lake Town Block A, Kolkata, Howrah, West ...",India

In [25]:
source2.head()

,entity_id,business_name,business_address,country
0,S2-166376419,राम मार्केटिंग प्राइवेट लिमिटेड,"KH NO. -570/13, NEW DELHI, WEST DELHI, Delhi",India
1,S2-764573417,-- Holloway Peak Inc Seafood,"105 ELM ST, MORGANTON, NC",US
2,S2-639257739,आदित्य प्रॉपर्टीज एलएलपी,"G-3/571, GULMOHAR COLONY, BHOPAL, Madhya Pradesh",India
3,S2-163963287,Summit Inc,"GREENSBORO, NC, 19 1/2 STARDUST TRAIL",US
4,S2-49942811,Delta Tetlecommunication Inc,"914 PIERPONT AVE, CLEVELAND, OH",US

In [17]:
source3.head()

,entity_id,business_name,business_address,country
0,S3-202863386,wilfordhancock.com,"Mack Rd, Haltom City, Texas",US
1,S3-859268022,International South Consultants Private Ltd,NaN,India
2,S3-22467283,LLC Moncada Léarning Center,"5780 Fawn Ct, Fort Worth, Texas",US
3,S3-671162755,Moyna's Coffee,"1 Ivanhoe Ave, PO Box 6009, Cincinnati, Ohio",US
4,S3-960981775,Pvt. EFS Print Ventures Ltd.,"Door No 183, 41St Cross, 22Nd Main 9Th Block J...",India

In [26]:
import re
import unicodedata

def clean_text(text):
    if pd.isna(text):
        return ""
    
    text = str(text)
    
    # Normalize Unicode characters
    text = unicodedata.normalize("NFKC", text)
    
    # Convert English characters to lowercase
    text = text.lower()
    
    # Remove extra spaces
    text = re.sub(r"\s+", " ", text)
    
    # Remove leading/trailing spaces
    text = text.strip()
    
    return text

In [27]:
for df in [source1, source2, source3]:
    df["business_name_clean"] = df["business_name"].apply(clean_text)
    df["business_address_clean"] = df["business_address"].apply(clean_text)
    df["country_clean"] = df["country"].apply(clean_text)

In [28]:
display(source1)

,entity_id,business_name,business_address,country,business_name_clean,business_address_clean,country_clean
0,S1-925783039,Orelee's Barbershop,"1795 Westchester Drive, High Point, NC",US,orelee's barbershop,"1795 westchester drive, high point, nc",us
1,S1-773889195,Prime Money,"17560 Ellis Road, Tahlequah, OK",US,prime money,"17560 ellis road, tahlequah, ok",us
2,S1-377745466,B+ Retail Inc,"1712 Montebello Avenue, Phoenix, AZ",US,b+ retail inc,"1712 montebello avenue, phoenix, az",us
3,S1-133037285,Christ Chapel,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",US,christ chapel,"2100 cameron drive, unit apartment g, dundalk, md",us
4,S1-755362802,Prabhav Business Center,"797, Lake Town Block A, Kolkata, Howrah, West ...",India,prabhav business center,"797, lake town block a, kolkata, howrah, west ...",india

In [21]:
print(source1.isnull().sum())
print(source2.isnull().sum())
print(source3.isnull().sum())

entity_id                 0
business_name             0
business_address          0
country                   0
business_name_clean       0
business_address_clean    0
country_clean             0
dtype: int64
entity_id                 0
business_name             0
business_address          0
country                   0
business_name_clean       0
business_address_clean    0
country_clean             0
dtype: int64
entity_id                 0
business_name             0
business_address          1
country                   0
business_name_clean       0
business_address_clean    0
country_clean             0
dtype: int64

In [29]:
print(group.head(10).to_string())
print("Shape:", group.shape)

  source1_entity_id                                                             matched_entity_ids
0         S1-965667                S2-681193310,S2-743505751,S3-775321672,S3-11291185,S3-860443364
1       S1-55344266                            S2-249013014,S2-197070651,S3-478195123,S3-384364074
2      S1-343815751                                         S2-790675320,S2-479876582,S3-878454467
3      S1-656753428                                          S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-728090388,S3-928796641,S3-449308785
5       S1-18727616                            S2-755677256,S3-187831601,S3-641489370,S3-476250621
6      S1-318373630                                                      S2-660036492,S3-804600254
7       S1-86989137                                                      S3-274817120,S3-312496301
8       S1-29845983                                                      S2-648035184,S3-588502663
9      S1-789009573                                          S2-383871912,S3-74481402,S3-576451439
Shape: (10, 2)

In [30]:
display(source2)

,entity_id,business_name,business_address,country,business_name_clean,business_address_clean,country_clean
0,S2-166376419,राम मार्केटिंग प्राइवेट लिमिटेड,"KH NO. -570/13, NEW DELHI, WEST DELHI, Delhi",India,राम मार्केटिंग प्राइवेट लिमिटेड,"kh no. -570/13, new delhi, west delhi, delhi",india
1,S2-764573417,-- Holloway Peak Inc Seafood,"105 ELM ST, MORGANTON, NC",US,-- holloway peak inc seafood,"105 elm st, morganton, nc",us
2,S2-639257739,आदित्य प्रॉपर्टीज एलएलपी,"G-3/571, GULMOHAR COLONY, BHOPAL, Madhya Pradesh",India,आदित्य प्रॉपर्टीज एलएलपी,"g-3/571, gulmohar colony, bhopal, madhya pradesh",india
3,S2-163963287,Summit Inc,"GREENSBORO, NC, 19 1/2 STARDUST TRAIL",US,summit inc,"greensboro, nc, 19 1/2 stardust trail",us
4,S2-49942811,Delta Tetlecommunication Inc,"914 PIERPONT AVE, CLEVELAND, OH",US,delta tetlecommunication inc,"914 pierpont ave, cleveland, oh",us

In [34]:
group = pd.read_csv("6ab10eb3b23ba_student_resource/student_resource/dataset/train/train_ground_truth.tsv", sep="\t")

print(group.shape)
group.head()

(2206821, 2)

  source1_entity_id                                 matched_entity_ids
0         S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1       S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2      S1-343815751             S2-790675320,S2-479876582,S3-878454467
3      S1-656753428              S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...

In [35]:
# Number of matched entities in each row
num_matches = group["matched_entity_ids"].str.count(",") + 1

print("Source 1 entities:", len(group))
print("Total positive pairs:", num_matches.sum())
print("Average matches per Source 1:", num_matches.mean())
print("Maximum matches for one Source 1:", num_matches.max())

Source 1 entities: 2206821
Total positive pairs: 7638365.0
Average matches per Source 1: 3.66599170463828
Maximum matches for one Source 1: 11.0